name: Maintain backlinks in wiki
description: Add or update a backlinks section to each wiki page.
runs:
  using: "composite"
  steps:
    - run: yarn install && yarn run build
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: |
        ${{ github.action_path }}/dist/index.js .
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update backlinks" || true
        git push
      shell: bash
